// Generated by dali-ui preprocessor. Do not modify.
#pragma once

#define DALI_UI_CHAIN_SCROLLVIEW_METHODS(ChildClass) \
  DALI_UI_CHAIN_VIEW_METHODS(ChildClass) \
  /** \
  * @brief Sets the content view to be scrolled. \
  * \
  * @param[in] content The content view \
  */ \
  ChildClass& SetContent(View content) { ScrollView::SetContent(content); return *this; } \
  /** \
  * @brief Sets the scroll position. \
  * \
  * @param[in] position The scroll position to set \
  */ \
  ChildClass& SetScrollPosition(const Vector2& position) { ScrollView::SetScrollPosition(position); return *this; } \
  /** \
  * @brief Sets the direction of the scroll. \
  * \
  * @param[in] direction The scroll direction \
  */ \
  ChildClass& SetScrollDirection(ScrollDirection direction) { ScrollView::SetScrollDirection(direction); return *this; } \
  /** \
  * @brief Sets the maximum distance by fling action. \
  * \
  * @param[in] distance The maximum fling distance \
  */ \
  ChildClass& SetMaxFlingDistance(float distance) { ScrollView::SetMaxFlingDistance(distance); return *this; } \
  /** \
  * @brief Sets the minimum duration of fling scroll animation. \
  * \
  * @param[in] duration The minimum fling duration \
  */ \
  ChildClass& SetMinimumFlingDuration(int duration) { ScrollView::SetMinimumFlingDuration(duration); return *this; } \
  /** \
  * @brief Sets the maximum duration of fling scroll animation. \
  * \
  * @param[in] duration The maximum fling duration \
  */ \
  ChildClass& SetMaximumFlingDuration(int duration) { ScrollView::SetMaximumFlingDuration(duration); return *this; } \
  /** \
  * @brief Sets the sensitivity of fling action. \
  * \
  * @param[in] sensitivity The fling sensitivity \
  */ \
  ChildClass& SetFlingSensitivity(float sensitivity) { ScrollView::SetFlingSensitivity(sensitivity); return *this; } \
  /** \
  * @brief Sets the deceleration rate of fling. \
  * \
  * @param[in] rate The deceleration rate \
  */ \
  ChildClass& SetDecelerationRate(float rate) { ScrollView::SetDecelerationRate(rate); return *this; } \
  /** \
  * @brief Sets the over scroll mode. \
  * \
  * @param[in] mode The over scroll mode \
  */ \
  ChildClass& SetOverScrollMode(OverScrollMode mode) { ScrollView::SetOverScrollMode(mode); return *this; } \
  /** \
  * @brief Sets whether to automatically scroll to a child view when it gains focus. \
  * \
  * When enabled, any descendant of the scroll content that gains keyboard focus \
  * will be scrolled into view according to the position set by SetFocusScrollToPosition(). \
  * \
  * @param[in] enable True to enable auto-scroll on focus (default: true) \
  */ \
  ChildClass& SetScrollOnFocus(bool enable) { ScrollView::SetScrollOnFocus(enable); return *this; } \
  /** \
  * @brief Sets the target scroll position used when auto-scrolling to a focused child. \
  * \
  * @param[in] position The target scroll position (default: ScrollToPosition::MakeVisible) \
  * @see ScrollToPosition \
  */ \
  ChildClass& SetFocusScrollToPosition(ScrollToPosition position) { ScrollView::SetFocusScrollToPosition(position); return *this; } \
  /** \
  * @brief Sets the peek distance applied when auto-scrolling to a focused child. \
  * \
  * When @p peek is greater than zero and the scroll mode is ScrollToPosition::MakeVisible, \
  * the view scrolls an additional @p peek pixels past the item edge in the direction of \
  * travel. This hints to the user that more content is available beyond the focused item. \
  * \
  * The final position is still clamped to the valid scroll range, so peek is silently \
  * reduced near the content boundaries. \
  * \
  * @param[in] peek Extra scroll distance in pixels (default: 0.0f, disabled) \
  */ \
  ChildClass& SetFocusScrollPeek(float peek) { ScrollView::SetFocusScrollPeek(peek); return *this; } \
  /** \
  * @brief Sets whether key-based step scrolling is enabled. \
  * \
  * When enabled, ScrollView intercepts focus navigation requests (UP/DOWN/LEFT/RIGHT/ \
  * PAGE_UP/PAGE_DOWN) from its content children. If the next focusable view in that \
  * direction is within GetKeyScrollStep() pixels it receives focus as normal; otherwise \
  * the ScrollView scrolls by one step instead, keeping the focus where it is. \
  * \
  * This gives a "gradual reveal" UX on keyboard/remote-control navigation: the user \
  * scrolls through content one step at a time and focus only jumps to a new item when \
  * that item is close enough to be immediately visible. \
  * \
  * @param[in] enable True to enable (default: false) \
  */ \
  ChildClass& SetKeyScrollEnabled(bool enable) { ScrollView::SetKeyScrollEnabled(enable); return *this; } \
  /** \
  * @brief Sets the step distance used for key-based step scrolling. \
  * \
  * Serves as both the proximity threshold and the scroll step size: \
  * - Next focusable is within @p step px  → focus moves there. \
  * - Next focusable is beyond @p step px, or none → scroll by @p step px. \
  * PAGE_UP / PAGE_DOWN always scrolls by the full viewport size regardless of this value. \
  * \
  * @param[in] step Step distance in pixels (default: 200.0f) \
  */ \
  ChildClass& SetKeyScrollStep(float step) { ScrollView::SetKeyScrollStep(step); return *this; } \
  /** \
  * @brief Sets the visibility of the vertical scroll bar. \
  * \
  * @param[in] visibility The vertical scroll bar visibility \
  */ \
  ChildClass& SetVerticalScrollBarVisibility(ScrollBarVisibility visibility) { ScrollView::SetVerticalScrollBarVisibility(visibility); return *this; } \
  /** \
  * @brief Sets the visibility of the horizontal scroll bar. \
  * \
  * @param[in] visibility The horizontal scroll bar visibility \
  */ \
  ChildClass& SetHorizontalScrollBarVisibility(ScrollBarVisibility visibility) { ScrollView::SetHorizontalScrollBarVisibility(visibility); return *this; }
